# Generated by Django 5.2.15 on 2026-06-07 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('niveau_alerte_actuel', models.CharField(choices=[('vert', 'Vert (Normal)'), ('jaune', 'Jaune (Vigilance)'), ('orange', 'Orange (Alerte)'), ('rouge', 'Rouge (Urgence)')], default='vert', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_eau_cm', models.FloatField()),
                ('pluviometrie_mm', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='api.zone')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('vert', 'Vert (Normal)'), ('jaune', 'Jaune (Vigilance)'), ('orange', 'Orange (Alerte)'), ('rouge', 'Rouge (Urgence)')], max_length=10)),
                ('message', models.TextField()),
                ('date_declenchement', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='api.zone')),
            ],
            options={
                'ordering': ['-date_declenchement'],
            },
        ),
    ]
