# Generated by Django 5.2.15 on 2026-06-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('inondation', 'Inondation / Montée des eaux'), ('egout_bouche', 'Égout bouché'), ('dechets', "Déchets accumulés empêchant l'eau de couler"), ('infrastructure', 'Infrastructure endommagée (route, pont)'), ('autre', 'Autre problème')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='signalements_photos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='nouveau', max_length=20)),
            ],
        ),
    ]
