# Generated by Django 5.0.8 on 2026-08-17 15:28

import api.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('eau', 'Eau'), ('pluviometre', 'Pluviomètre')], max_length=20)),
                ('localisation', api.fields.SpatialPointField(max_length=255, spatial_index=True, srid=4326)),
                ('actif', models.BooleanField(default=True)),
                ('date_installation', models.DateField()),
            ],
            options={
                'verbose_name': 'Capteur',
                'verbose_name_plural': 'Capteurs',
            },
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('unite', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='capteurs.capteur')),
            ],
            options={
                'verbose_name': 'Mesure',
                'verbose_name_plural': 'Mesures',
                'ordering': ['-timestamp'],
            },
        ),
    ]
