# Generated by Django 5.0.3 on 2026-09-09 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0002_historiquerisque_previsionmeteo_and_more'),
        ('capteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='code_identifiant',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='capteur',
            name='dernier_releve',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capteur',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('maintenance', 'En maintenance')], default='actif', max_length=20),
        ),
        migrations.AddField(
            model_name='capteur',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capteurs', to='alertes.zonerisque'),
        ),
    ]
