# Generated by Django 5.0.3 on 2026-09-10 19:17

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0002_capteur_code_identifiant_capteur_dernier_releve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='localisation',
            field=api.fields.SpatialPointField(srid=4326),
        ),
    ]
