# Generated by Django 5.0.3 on 2026-09-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0003_alter_capteur_localisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capteur',
            name='actif',
        ),
    ]
