# Generated by Django 5.0.8 on 2026-08-17 15:28

import api.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeInondation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', api.fields.SpatialMultiPolygonField(spatial_index=True, srid=4326)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('surface_ha', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Épisode d'inondation",
                'verbose_name_plural': "Épisodes d'inondations",
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='SignalementCitoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', api.fields.SpatialPointField(max_length=255, spatial_index=True, srid=4326)),
                ('description', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='signalements/')),
                ('valide', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.CharField(choices=[('egouts', 'Égouts'), ('inondation', 'Inondation'), ('autre', 'Autre')], default='autre', max_length=20)),
            ],
            options={
                'verbose_name': 'Signalement citoyen',
                'verbose_name_plural': 'Signalements citoyens',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ZoneRisque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', api.fields.SpatialPolygonField(spatial_index=True, srid=4326)),
                ('quartier', models.CharField(max_length=100)),
                ('niveau_risque', models.CharField(choices=[('vert', 'Vert'), ('jaune', 'Jaune'), ('orange', 'Orange'), ('rouge', 'Rouge')], max_length=20)),
            ],
            options={
                'verbose_name': 'Zone de risque',
                'verbose_name_plural': 'Zones de risque',
            },
        ),
        migrations.CreateModel(
            name='PredictionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilite', models.FloatField()),
                ('horizon_h', models.IntegerField()),
                ('confiance', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='alertes.zonerisque')),
            ],
            options={
                'verbose_name': 'Prédiction IA',
                'verbose_name_plural': 'Prédictions IA',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('vert', 'Vert'), ('jaune', 'Jaune'), ('orange', 'Orange'), ('rouge', 'Rouge')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('canaux', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoyee', 'Envoyée'), ('resolue', 'Résolue')], default='en_attente', max_length=20)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='alertes.zonerisque')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
