# Generated by Django 5.0.3 on 2026-09-09 20:53

import api.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueRisque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cible', models.CharField(choices=[('zone', 'Zone de risque'), ('segment', 'Segment de rue')], max_length=20)),
                ('cible_id', models.PositiveIntegerField()),
                ('score_risque', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historique de risque',
                'verbose_name_plural': 'Historiques de risque',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.CreateModel(
            name='PrevisionMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevision', models.DateTimeField()),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitesse_vent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prévision météo',
                'verbose_name_plural': 'Prévisions météo',
                'ordering': ['-date_prevision'],
            },
        ),
        migrations.AddField(
            model_name='alerte',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signalementcitoyen',
            name='signale_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonerisque',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zonerisque',
            name='score_risque_moyen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.CreateModel(
            name='SegmentRue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('geom', api.fields.SpatialLineStringField(spatial_index=True, srid=4326)),
                ('altitude_moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pente', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('etat_drainage', models.CharField(choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('obstrue', 'Obstrué'), ('inexistant', 'Inexistant')], default='bon', max_length=20)),
                ('score_risque_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='alertes.zonerisque')),
            ],
            options={
                'verbose_name': 'Segment de rue',
                'verbose_name_plural': 'Segments de rue',
            },
        ),
    ]
