# Generated by Django 5.0.3 on 2026-09-10 19:17

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0002_historiquerisque_previsionmeteo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalementcitoyen',
            name='localisation',
            field=api.fields.SpatialPointField(srid=4326),
        ),
    ]
