# Generated by Django 5.0.3 on 2026-09-10 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0003_alter_signalementcitoyen_localisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquerisque',
            name='cible_id',
        ),
        migrations.RemoveField(
            model_name='historiquerisque',
            name='type_cible',
        ),
        migrations.AddField(
            model_name='historiquerisque',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_risque', to='alertes.segmentrue'),
        ),
        migrations.AddField(
            model_name='historiquerisque',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_risque', to='alertes.zonerisque'),
        ),
        migrations.AddConstraint(
            model_name='historiquerisque',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('segment__isnull', True), ('zone__isnull', False)), models.Q(('segment__isnull', False), ('zone__isnull', True)), _connector='OR'), name='historique_risque_une_seule_cible'),
        ),
    ]
