# Generated by Django 5.0.3 on 2026-09-10 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0004_remove_historiquerisque_cible_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_alerte', to='alertes.zonerisque')),
            ],
            options={
                'verbose_name': "Contact d'alerte",
                'verbose_name_plural': "Contacts d'alerte",
                'ordering': ['-date_inscription'],
            },
        ),
    ]
