# Generated by Django 5.0.3 on 2026-09-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0005_contactalerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionia',
            name='niveau_eau_predit_cm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
