# Generated by Django 5.0.3 on 2026-09-15 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0006_predictionia_niveau_eau_predit_cm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilVulnerabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnes_agees', models.PositiveSmallIntegerField(default=0)),
                ('enfants_bas_age', models.PositiveSmallIntegerField(default=0)),
                ('personne_mobilite_reduite', models.BooleanField(default=False)),
                ('femme_enceinte', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_vulnerabilite', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils_vulnerabilite', to='alertes.zonerisque')),
            ],
            options={
                'verbose_name': 'Profil de vulnérabilité',
                'verbose_name_plural': 'Profils de vulnérabilité',
            },
        ),
        migrations.CreateModel(
            name='RelaisQuartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifie', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relais_quartier', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relais', to='alertes.zonerisque')),
            ],
            options={
                'verbose_name': 'Relais de quartier',
                'verbose_name_plural': 'Relais de quartier',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
