# Generated by Django 5.0.3 on 2026-09-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0007_profilvulnerabilite_relaisquartier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilvulnerabilite',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Profil de vulnérabilité', 'verbose_name_plural': 'Profils de vulnérabilité'},
        ),
    ]
