# Generated by Django 5.0.3 on 2026-09-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0008_alter_profilvulnerabilite_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalementcitoyen',
            name='niveau_eau_estime',
            field=models.CharField(choices=[('indetermine', 'Indéterminé'), ('faible', 'Faible'), ('modere', 'Modéré'), ('eleve', 'Élevé')], default='indetermine', max_length=20),
        ),
        migrations.AddField(
            model_name='signalementcitoyen',
            name='photo_hash',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='signalementcitoyen',
            name='score_eau_estime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalementcitoyen',
            name='signalement_similaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doublons_potentiels', to='alertes.signalementcitoyen'),
        ),
    ]
