# Generated by Django 5.0.8 on 2026-09-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0009_signalementcitoyen_niveau_eau_estime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodeinondation',
            name='is_synthetic',
            field=models.BooleanField(default=False, help_text='TRUE = donnée de test/démo, FALSE = vraie inondation observée'),
        ),
    ]
