# Generated by Django 5.0.8 on 2026-09-21 23:58

import api.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0010_episodeinondation_is_synthetic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRefuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_refuge', models.CharField(choices=[('ecole', 'École'), ('mosquee', 'Mosquée'), ('centre_sante', 'Centre de santé'), ('mairie', 'Mairie'), ('bâtiment_public', 'Bâtiment public'), ('autre', 'Autre')], max_length=50)),
                ('localisation', api.fields.SpatialPointField(srid=4326)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('quartier', models.CharField(max_length=100)),
                ('capacite', models.IntegerField(blank=True, help_text='Nombre de personnes max', null=True)),
                ('contact', models.CharField(blank=True, help_text='Numéro de téléphone du responsable', max_length=50)),
                ('hauteur_etage', models.IntegerField(blank=True, help_text="Nombre d'étages (pour refuges surélevés)", null=True)),
                ('notes', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refuges', to='alertes.zonerisque')),
            ],
            options={
                'verbose_name': 'Point de refuge',
                'verbose_name_plural': 'Points de refuge',
                'ordering': ['quartier', 'nom'],
            },
        ),
    ]
