# Generated by Django 5.0.8 on 2026-09-22 00:12

import api.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0011_pointrefuge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(help_text='Numéro du citoyen qui a envoyé le SMS', max_length=20)),
                ('contenu_sms', models.TextField(help_text='Texte du SMS reçu')),
                ('localisation_texte', models.CharField(blank=True, help_text='Localisation extraite du SMS', max_length=300)),
                ('localisation_geom', api.fields.SpatialPointField(blank=True, help_text='Coordonnées géographiques (si extractible)', null=True, srid=4326)),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('traitement', 'En traitement'), ('converti', 'Converti en signalement'), ('erreur', 'Erreur de traitement')], default='recu', max_length=20)),
                ('message_erreur', models.TextField(blank=True, help_text="Détail si statut='erreur'")),
                ('timestamp_recu', models.DateTimeField(auto_now_add=True)),
                ('timestamp_traite', models.DateTimeField(blank=True, null=True)),
                ('provider_id', models.CharField(blank=True, help_text='Identifiant externe du message', max_length=100)),
                ('provider_name', models.CharField(blank=True, help_text='Fournisseur SMS (twilio, infobip, etc.)', max_length=50)),
                ('signalement_cree', models.ForeignKey(blank=True, help_text='SignalementCitoyen créé à partir de ce SMS (si conversion réussie)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_source', to='alertes.signalementcitoyen')),
            ],
            options={
                'verbose_name': 'SMS signalement',
                'verbose_name_plural': 'SMS signalements',
                'ordering': ['-timestamp_recu'],
                'indexes': [models.Index(fields=['-timestamp_recu'], name='alertes_sms_timesta_bda2e9_idx'), models.Index(fields=['statut'], name='alertes_sms_statut_d35219_idx'), models.Index(fields=['telephone'], name='alertes_sms_telepho_781069_idx')],
            },
        ),
    ]
