# Generated by Django 5.0.8 on 2026-09-22 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0012_smssignalement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom du contact d'urgence", max_length=100)),
                ('relation', models.CharField(choices=[('famille', 'Famille'), ('ami', 'Ami'), ('voisin', 'Voisin'), ('medecin', 'Médecin'), ('autre', 'Autre')], help_text='Relation avec le contact', max_length=50)),
                ('telephone', models.CharField(help_text='Numéro de téléphone', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True, help_text='Adresse du contact')),
                ('alerter_automatiquement', models.BooleanField(default=True, help_text="Alerter automatiquement lors d'une alerte d'inondation")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Contact d'urgence",
                'verbose_name_plural': "Contacts d'urgence",
            },
        ),
        migrations.CreateModel(
            name='SurvivalKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eau_potable_litres', models.IntegerField(default=0, help_text="Litres d'eau potable stockée")),
                ('nourriture_jours', models.IntegerField(default=0, help_text='Jours de nourriture non-périssable')),
                ('medicaments', models.BooleanField(default=False, help_text='Médicaments essentiels disponibles')),
                ('documents_importants', models.BooleanField(default=False, help_text='Documents importants préparés')),
                ('lampe_torche', models.BooleanField(default=False)),
                ('batterie_portable', models.BooleanField(default=False)),
                ('trousse_premiers_secours', models.BooleanField(default=False)),
                ('vetements_secours', models.BooleanField(default=False)),
                ('plan_evacuation', models.TextField(blank=True, help_text="Plan d'évacuation personnel")),
                ('points_refuge_identifies', models.BooleanField(default=False)),
                ('voisins_contactes', models.BooleanField(default=False)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survival_kit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kit de survie',
                'verbose_name_plural': 'Kits de survie',
            },
        ),
    ]
