# Generated by Django 5.0.8 on 2026-09-22 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0013_emergencycontact_survivalkit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_citoyen', models.CharField(blank=True, help_text='Numéro de téléphone du citoyen si non identifié', max_length=20)),
                ('categorie', models.CharField(choices=[('electrique', 'Danger électronique'), ('eau', 'Eau potable & désinfectée'), ('evacuation', 'Évacuation réflexe & secours')], max_length=20)),
                ('date_appel', models.DateTimeField(auto_now_add=True)),
                ('duree_appel_minutes', models.IntegerField(default=0, help_text="Durée de l'appel en minutes")),
                ('reponses', models.JSONField(default=dict, help_text='Dictionnaire des réponses cochées et notes')),
                ('pourcentage_complete', models.IntegerField(default=0, help_text='Pourcentage de complétude du triage (0-100)')),
                ('notes_generales', models.TextField(blank=True, help_text="Notes générales sur l'appel")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('autorite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages_appels', to=settings.AUTH_USER_MODEL)),
                ('citoyen', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'citoyen'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appels_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Triage d'appel",
                'verbose_name_plural': "Triages d'appels",
                'ordering': ['-date_appel'],
                'indexes': [models.Index(fields=['citoyen', '-date_appel'], name='alertes_tri_citoyen_6c74ce_idx'), models.Index(fields=['autorite', '-date_appel'], name='alertes_tri_autorit_ca7644_idx'), models.Index(fields=['categorie', '-date_appel'], name='alertes_tri_categor_83bba4_idx')],
            },
        ),
    ]
