# Generated by Django 5.0.8 on 2026-09-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0014_triageappel'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonerisque',
            name='seuil_jaune',
            field=models.DecimalField(decimal_places=2, default=0.4, help_text='Score seuil pour alerte jaune (0-1)', max_digits=4),
        ),
        migrations.AddField(
            model_name='zonerisque',
            name='seuil_orange',
            field=models.DecimalField(decimal_places=2, default=0.65, help_text='Score seuil pour alerte orange (0-1)', max_digits=4),
        ),
        migrations.AddField(
            model_name='zonerisque',
            name='seuil_rouge',
            field=models.DecimalField(decimal_places=2, default=0.85, help_text='Score seuil pour alerte rouge (0-1)', max_digits=4),
        ),
    ]
