# Generated by Django 5.0.8 on 2026-09-22 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0015_zonerisque_seuil_jaune_zonerisque_seuil_orange_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previsionmeteo',
            name='precipitation',
        ),
        migrations.RemoveField(
            model_name='previsionmeteo',
            name='temperature',
        ),
        migrations.AddField(
            model_name='previsionmeteo',
            name='date_fin',
            field=models.DateTimeField(blank=True, help_text='Date fin si prévision multi-jours', null=True),
        ),
        migrations.AddField(
            model_name='previsionmeteo',
            name='humidity_percent',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Humidité relative %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='previsionmeteo',
            name='precipitation_mm',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Précipitation en mm', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previsionmeteo',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Température en °C', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='previsionmeteo',
            name='temperature_max_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='previsionmeteo',
            name='temperature_min_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='previsionmeteo',
            name='weather_code',
            field=models.IntegerField(blank=True, help_text='Code météo WMO', null=True),
        ),
        migrations.AddField(
            model_name='previsionmeteo',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsions_meteo', to='alertes.zonerisque'),
        ),
        migrations.AlterField(
            model_name='previsionmeteo',
            name='source',
            field=models.CharField(default='open-meteo', help_text='Source: open-meteo, anacim, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='previsionmeteo',
            name='vitesse_vent',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Vitesse vent km/h', max_digits=4, null=True),
        ),
        migrations.AddIndex(
            model_name='previsionmeteo',
            index=models.Index(fields=['date_prevision'], name='alertes_pre_date_pr_4d6307_idx'),
        ),
        migrations.AddIndex(
            model_name='previsionmeteo',
            index=models.Index(fields=['zone', 'date_prevision'], name='alertes_pre_zone_id_2e5fb2_idx'),
        ),
    ]
