# Generated by Django 5.0.8 on 2026-09-22 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0016_remove_previsionmeteo_precipitation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('alert_created', 'Alerte créée'), ('threshold_changed', 'Seuil modifié'), ('crisis_started', 'Crise démarrée'), ('crisis_resolved', 'Crise résolue'), ('sms_sent', 'SMS envoyé'), ('push_sent', 'Notification Push envoyée'), ('report_generated', 'Rapport généré'), ('user_modified', 'Utilisateur modifié'), ('zone_updated', 'Zone mise à jour'), ('other', 'Autre')], help_text="Type d'action effectuée", max_length=50)),
                ('description', models.TextField(help_text="Description détaillée de l'action")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (zone_id, seuil_ancien, seuil_nouveau, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('authority', models.ForeignKey(help_text="Autorité qui a effectué l'action", on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité",
                'verbose_name_plural': "Logs d'activité",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['authority', '-timestamp'], name='alertes_act_authori_609612_idx'), models.Index(fields=['action_type', '-timestamp'], name='alertes_act_action__a3168f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrisisManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crisis_date', models.DateTimeField(help_text='Date et heure du début de la crise')),
                ('status', models.CharField(choices=[('ongoing', 'En cours'), ('resolved', 'Résolue'), ('archived', 'Archivée')], default='ongoing', help_text='Statut actuel de la crise', max_length=20)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, help_text='Heures de travail consacrées à cette crise', max_digits=5)),
                ('notifications_sent', models.IntegerField(default=0, help_text='Nombre de SMS et notifications Push envoyés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Date de résolution de la crise', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes et observations sur la gestion de la crise')),
                ('authority', models.ForeignKey(help_text='Autorité responsable de la gestion de la crise', on_delete=django.db.models.deletion.CASCADE, related_name='crisis_management', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, help_text='Zone affectée par la crise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crisis_management', to='alertes.zonerisque')),
            ],
            options={
                'verbose_name': 'Gestion de crise',
                'verbose_name_plural': 'Gestions de crise',
                'ordering': ['-crisis_date'],
                'indexes': [models.Index(fields=['authority', '-crisis_date'], name='alertes_cri_authori_5b855f_idx'), models.Index(fields=['status', '-crisis_date'], name='alertes_cri_status_f683d7_idx'), models.Index(fields=['zone', '-crisis_date'], name='alertes_cri_zone_id_79a5c9_idx')],
            },
        ),
    ]
