# Generated by Django 5.0.8 on 2026-09-22 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0017_activitylog_crisismanagement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisismanagement',
            name='authority',
        ),
        migrations.RemoveField(
            model_name='crisismanagement',
            name='zone',
        ),
        migrations.AddField(
            model_name='alerte',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='CrisisManagement',
        ),
    ]
