# Generated by Django 5.0.3 on 2026-09-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('autorite', 'Autorité'), ('agent', 'Agent terrain'), ('citoyen', 'Citoyen')], default='citoyen', max_length=20),
        ),
    ]
