# Generated by Django 5.0.8 on 2026-09-21 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_invitecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={'verbose_name': "Code d'invitation Admin", 'verbose_name_plural': "Codes d'invitation Admin"},
        ),
        migrations.RemoveField(
            model_name='invitecode',
            name='role',
        ),
        migrations.AddField(
            model_name='invitecode',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_invites_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_invites_used', to=settings.AUTH_USER_MODEL),
        ),
    ]
