# Generated by Django 5.0.8 on 2026-09-22 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_invitecode_options_remove_invitecode_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crises_gerees', models.IntegerField(default=0, help_text='Nombre de crises gérées')),
                ('requetes_traitees', models.IntegerField(default=0, help_text='Nombre de requêtes/signalements traités')),
                ('alertes_envoyees', models.IntegerField(default=0, help_text="Nombre d'alertes envoyées")),
                ('heures_travail', models.DecimalField(decimal_places=1, default=0, help_text='Heures de travail estimées', max_digits=5)),
                ('date_creation_compte', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('premiere_action', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorities_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Suivi d'autorité",
                'verbose_name_plural': "Suivi d'autorités",
            },
        ),
    ]
