# Generated by Django 5.0.8 on 2026-09-22 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_authoritytracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('alert_sent', 'Alerte envoyée'), ('request_handled', 'Requête traitée'), ('crisis_managed', 'Crise gérée'), ('login', 'Connexion'), ('dashboard_view', 'Dashboard consulté'), ('report_generated', 'Rapport généré')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('zone', models.CharField(blank=True, help_text='Zone concernée si applicable', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Activité d'autorité",
                'verbose_name_plural': "Activités d'autorité",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['authority', '-timestamp'], name='users_autho_authori_91bbc8_idx')],
            },
        ),
    ]
