# Generated by Django 5.0.8 on 2026-10-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_authorityactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_requise',
            field=models.BooleanField(default=False, help_text="La connexion est refusée tant que le code OTP n'a pas été validé"),
        ),
    ]
