// Chapitre I : cadre théorique et conceptuel (cible : 6 pages)
module.exports = ({ H1, H2, H3, H4, P, B, figure, tableBlock }) => [
  H1('CHAPITRE I : CADRE THÉORIQUE ET CONCEPTUEL'),
  P("Ce chapitre définit les notions sur lesquelles repose le travail (section 1), puis situe MBEUND MI par rapport aux SIG, à la télédétection et aux solutions numériques existantes en Afrique (section 2)."),

  H2('Section 1 : Revue conceptuelle'),
  H3('Sous-section 1 : Les inondations urbaines et côtières — définitions et typologie'),
  P("Une **inondation** est la submersion temporaire d'une zone habituellement hors d'eau. Elle devient un problème lorsqu'elle touche des personnes, des biens ou des activités. La terminologie des Nations Unies (Assemblée générale des Nations Unies, 2016) distingue l'**aléa**, phénomène susceptible de causer des dommages (pluie intense, remontée de nappe, submersion marine) ; les **enjeux** exposés (personnes, logements, commerces, routes) ; la **vulnérabilité**, c'est-à-dire les conditions qui rendent ces enjeux plus ou moins sensibles (qualité du bâti, assainissement, revenus, âge, accès à l'information) ; le **risque**, qui combine aléa et vulnérabilité, souvent résumé par *risque = aléa × vulnérabilité* ; enfin la **résilience**, capacité d'une communauté à absorber le choc et à se rétablir. Une plateforme numérique n'agit pas sur l'aléa, mais elle peut réduire la vulnérabilité en informant plus tôt et renforcer la résilience en aidant à s'organiser."),
  P("Selon l'origine de l'eau, on distingue plusieurs types d'inondation, dont la pertinence pour Thiaroye-sur-Mer varie (tableau 2).", { keepNext: true }),
  ...tableBlock('Tableau', 'Principaux types d\'inondation et pertinence pour Thiaroye-sur-Mer',
    ['Type', 'Mécanisme', 'Pertinence à Thiaroye-sur-Mer'],
    [
      ['Pluviale (ruissellement urbain)', 'Pluies intenses dépassant la capacité d\'infiltration et d\'évacuation ; accumulation dans les points bas. Cinétique rapide.', '**Forte** : cause principale citée par les habitants (caniveaux absents ou insuffisants).'],
      ['Par remontée de nappe', 'Nappe rechargée par les pluies atteignant la surface ; sol saturé. Cinétique lente, longue durée.', '**Forte** : nappe très proche de la surface dans la banlieue de Dakar.'],
      ['Côtière (submersion marine)', 'Houle, marées et surcotes de tempête, aggravées par l\'élévation du niveau marin et l\'érosion.', '**Moyenne** : zone d\'étude à 150-350 m du rivage ; la mer gêne aussi l\'évacuation des eaux.'],
      ['Fluviale', 'Débordement d\'un cours d\'eau après de fortes pluies sur son bassin.', '**Faible** : pas de cours d\'eau permanent dans la commune.'],
    ], [1900, 3900, 3270], 'synthèse des auteures.'),
  P("Dans les villes côtières basses, ces mécanismes se combinent en **inondation composée** : une pluie intense sur un sol déjà saturé par la nappe, là où la mer freine l'écoulement, produit une inondation plus étendue et plus durable, ce qui explique que l'eau stagne parfois plusieurs jours. Ces inondations sont aggravées par l'imperméabilisation des sols, l'occupation d'anciennes zones basses, l'insuffisance et le mauvais entretien des caniveaux, et le changement climatique : le niveau moyen des mers a augmenté d'environ 0,20 m entre 1901 et 2018 (GIEC, 2021). Ces facteurs étant en grande partie humains, ils peuvent être corrigés à condition d'être connus, localisés et suivis."),

  H3('Sous-section 2 : La gestion des risques de catastrophes (GRC) et les systèmes d\'alerte précoce'),
  P("La réponse aux catastrophes s'est longtemps limitée aux secours. La **gestion des risques de catastrophes (GRC)** vise au contraire à agir avant l'événement. Sa référence actuelle, le **Cadre de Sendai pour la réduction des risques de catastrophe 2015-2030**, fixe quatre priorités : comprendre les risques, renforcer leur gouvernance, investir dans leur réduction et améliorer la préparation pour « reconstruire en mieux » ; sa cible G vise un accès nettement accru aux systèmes d'alerte précoce (UNISDR, 2015). La GRC se représente comme un cycle en quatre phases (figure 1). MBEUND MI intervient surtout dans la **préparation** et la **réponse**, mais contribue aussi à la prévention, en cartographiant les secteurs exposés, et au relèvement, en conservant l'historique des épisodes."),
  ...figure('cycle_grc.png', 380, 285, 'Figure', 'Le cycle de la gestion des risques de catastrophes', 'adapté de la littérature sur la GRC ; réalisation des auteures.'),
  P("Un **système d'alerte précoce (SAP)** est un dispositif intégré de surveillance, de prévision, d'évaluation des risques, de communication et de préparation, qui permet d'agir à temps pour réduire les dommages (Assemblée générale des Nations Unies, 2016). Il repose sur **quatre piliers** interdépendants : la connaissance des risques ; la surveillance et la prévision ; la diffusion de l'alerte ; la capacité de préparation et de réaction (UNISDR, 2006 ; OMM, 2018). Un SAP vaut ce que vaut son pilier le plus faible : une bonne prévision est inutile si l'alerte n'atteint pas le « dernier kilomètre », c'est-à-dire les personnes les plus exposées. C'est l'objet de l'initiative des Nations Unies **« Alertes précoces pour tous »**, qui vise à protéger chaque personne par un SAP d'ici fin 2027 (OMM, 2022). Le tableau 3 montre comment MBEUND MI couvre chacun des piliers ; il sert de fil conducteur aux chapitres III et IV.", { keepNext: true }),
  ...tableBlock('Tableau', 'Les quatre piliers d\'un système d\'alerte précoce dans MBEUND MI',
    ['Pilier', 'Fonctionnalités de MBEUND MI'],
    [
      ['1. Connaissance des risques', 'Zones de risque cartographiées, avec seuils d\'alerte propres à chaque zone ; tronçons de rue et état du drainage ; historique des épisodes ; profil de vulnérabilité des foyers.'],
      ['2. Surveillance et prévision', 'Prévisions météorologiques toutes les 3 h ; capteurs (simulés) via MQTT avec contrôle des anomalies ; détection satellitaire de l\'eau (Sentinel-2, NDWI) toutes les 12 h ; classification du risque (Random Forest) et prédiction du niveau d\'eau (LSTM) toutes les 6 h.'],
      ['3. Diffusion de l\'alerte', 'Alertes en temps réel dans l\'application ; notifications push ; SMS aux inscrits de la zone, même sans smartphone ; messages en français et en wolof ; assistant NDAM.'],
      ['4. Préparation et réaction', 'Points de refuge et itinéraire d\'évacuation sûr ; kit de survie et contacts d\'urgence ; relais de quartier ; signalements validés par l\'autorité ; outils de gestion de crise.'],
    ], [2300, 6770], 'code source de MBEUND MI ; synthèse des auteures.'),
  P("Le numérique renforce chacun de ces piliers : satellites et capteurs connectés pour l'observation, téléphones mobiles pour diffuser l'alerte et recueillir les observations des habitants, devenus des « capteurs » humains (Goodchild, 2007). L'**apprentissage automatique** exploite ces données : les forêts aléatoires (Random Forest) sont robustes et peu exigeantes en réglage (Breiman, 2001) ; les réseaux LSTM, conçus pour les séries temporelles (Hochreiter et Schmidhuber, 1997), modélisent bien la transformation de la pluie en écoulement (Kratzert et al., 2018) et servent à la prévision mondiale des crues (Nearing et al., 2024). Leurs limites sont connues : un modèle ne vaut que par ses données d'entraînement, rares en Afrique de l'Ouest et inexistantes en hauteur d'eau pour Thiaroye-sur-Mer ; l'accès au numérique reste inégal. D'où deux choix de MBEUND MI : un canal SMS en complément de l'application, et une validation humaine des signalements."),

  H2('Section 2 : Revue de littérature et état de l\'art'),
  H3('Sous-section 1 : Les systèmes d\'information géographique (SIG) appliqués aux inondations'),
  P("Un **SIG** est un ensemble d'outils pour collecter, stocker, analyser et représenter des données localisées ; il superpose des couches d'information et permet de les interroger pour éclairer la décision (Longley et al., 2005). Les données **vecteur** décrivent des points (un signalement), des lignes (une rue) ou des polygones (une zone de risque) ; les données **raster** sont des grilles, comme une image satellite. Toutes doivent partager un même système de coordonnées, ici le WGS 84 (EPSG:4326). Les bases de données spatiales comme **PostGIS** réalisent les calculs géographiques directement dans la base, et des bibliothèques web comme **Leaflet** affichent ces données sur un téléphone : le SIG devient accessible au public."),
  P("Pour cartographier la susceptibilité aux inondations, deux familles de méthodes coexistent. Les **méthodes multicritères**, comme la hiérarchie multicritère de Saaty (1980), pondèrent les facteurs (altitude, pente, sols, occupation du sol) à dire d'experts : elles sont explicables mais subjectives. Les **méthodes d'apprentissage automatique** apprennent ces pondérations à partir d'inondations observées ; Tehrany et al. (2014), dans une étude menée en Malaisie, montrent que le couplage SIG et apprentissage améliore la précision des cartes. Ce couplage, repris par MBEUND MI, suppose un inventaire fiable des inondations passées, qui manque encore à Thiaroye-sur-Mer."),
  P("La **télédétection** repère les surfaces en eau sur de grandes étendues. L'indice **NDWI**, calculé à partir des bandes verte et proche infrarouge, fait ressortir l'eau libre (McFeeters, 1996) ; sa variante MNDWI distingue mieux l'eau du bâti (Xu, 2006). **Google Earth Engine** donne un accès gratuit aux archives Landsat et Sentinel et aux moyens de calcul (Gorelick et al., 2017). MBEUND MI calcule le NDWI sur des images **Sentinel-2** et compare saison sèche et période récente. Limite connue : l'optique ne traverse pas les nuages, fréquents en hivernage ; le radar **Sentinel-1** en est l'évolution naturelle."),
  P("Enfin, une part croissante de l'information géographique est produite par les citoyens (OpenStreetMap, applications de signalement) : c'est l'**information géographique volontaire** (Goodchild, 2007). Les **SIG participatifs** améliorent la pertinence et l'appropriation des cartes dans les pays en développement (Rambaldi et al., 2006), à condition de valider des données de qualité variable. Au Sénégal, l'usage des SIG pour les inondations s'est développé surtout par des projets financés de l'extérieur, comme le PROGEP de l'ADM et de la Banque mondiale [[À VÉRIFIER : intitulé exact et période]]. Il se heurte à des données anciennes, au coût des logiciels propriétaires, au manque de compétences pérennes et à la faible interopérabilité entre institutions. D'où le choix, pour MBEUND MI, de technologies libres et interopérables (PostgreSQL/PostGIS, Django, React, GeoJSON)."),

  H3('Sous-section 2 : Solutions numériques existantes de gestion des inondations en Afrique'),
  P("Trois familles de solutions coexistent en Afrique. Les **systèmes mondiaux** de prévision, comme **Google Flood Hub**, fondé sur des modèles LSTM capables de prévoir les crues même dans des bassins sans station (Nearing et al., 2024), et **GloFAS**, système européen Copernicus de prévision des débits des grands fleuves. Les **dispositifs régionaux**, comme le projet **FANFAR**, qui a développé avec AGRHYMET un système de prévision des crues pour l'Afrique de l'Ouest [[À VÉRIFIER : période et partenaires]], et, au Sénégal, les bulletins de l'**ANACIM**. Les **plateformes participatives** enfin, comme **Ushahidi**, née au Kenya en 2008 pour cartographier des signalements reçus par SMS ou par le web, ou **Ramani Huria**, qui a mobilisé étudiants et habitants de Dar es Salaam pour cartographier dans OpenStreetMap les zones inondables et les réseaux de drainage. Le tableau 4 les compare.", { keepNext: true }),
  ...tableBlock('Tableau', 'Comparaison des solutions numériques existantes et de MBEUND MI',
    ['Solution', 'Échelle', 'Inondations', 'Participation', 'Limite pour Thiaroye-sur-Mer'],
    [
      ['Google Flood Hub', 'Mondiale', 'Fluviales', 'Non', 'Pas de prévision des inondations pluviales urbaines.'],
      ['GloFAS', 'Mondiale', 'Fluviales', 'Non', 'Résolution inadaptée à une commune.'],
      ['FANFAR', 'Afrique de l\'Ouest', 'Fluviales', 'Non', 'Échelle régionale, pour les services techniques.'],
      ['Bulletins ANACIM', 'Nationale', 'Aléa météo', 'Non', 'Pas de déclinaison par quartier.'],
      ['Ushahidi', 'Variable', 'Signalements', 'Oui', 'Ni prévision ni alerte automatique.'],
      ['Ramani Huria', 'Ville', 'Cartographie', 'Oui', 'Pas de suivi en temps réel.'],
      ['**MBEUND MI**', '**Commune, quartier**', '**Pluviales, nappe**', '**Oui (appli, SMS)**', '**Prototype : capteurs simulés, modèles à réentraîner.**'],
    ], [1700, 1600, 1500, 1500, 2770], 'documentation publique des solutions citées ; synthèse des auteures.'),
  P("Cinq leçons en découlent pour MBEUND MI : **la granularité locale**, car les inondations pluviales et phréatiques d'un quartier ne sont couvertes par aucun système existant ; **la combinaison des sources**, aucune ne suffisant seule ; **l'accessibilité**, le SMS restant indispensable ; **la place de l'humain**, les signalements devant être validés et les prévisions aider la décision sans la remplacer ; **la pérennité**, que favorisent des technologies libres et documentées."),

  H3('Conclusion du chapitre'),
  P("Thiaroye-sur-Mer subit des inondations composées, pluviales, phréatiques et côtières, dont la gestion moderne repose sur l'alerte précoce et ses quatre piliers. Les solutions existantes en Afrique traitent surtout les crues fluviales à grande échelle : le besoin d'un outil local combinant prévision, alerte et participation reste ouvert. Le chapitre II décrit le contexte où il s'exprime."),
];
