// Chapitre III : cadre méthodologique et conception (cible : 10 pages)
module.exports = ({ H1, H2, H3, H4, P, B, figure, tableBlock }) => [
  H1('CHAPITRE III : CADRE MÉTHODOLOGIQUE ET CONCEPTION'),
  P("Ce chapitre décrit le passage du besoin au système. La première section spécifie les besoins, justifie les méthodes de modélisation et présente les principaux diagrammes UML ; la seconde expose les choix technologiques et le dispositif d'expérimentation. Tous les éléments présentés ici sont tirés du code source de la plateforme."),

  H2('Section 1 : Spécification et modélisation du système'),
  H3('Sous-section 1 : Spécification des besoins fonctionnels et non fonctionnels'),
  P("L'analyse documentaire et l'enquête de terrain ont permis d'identifier quatre **acteurs humains**, qui correspondent aux quatre rôles gérés par la plateforme : le **citoyen**, habitant de Thiaroye-sur-Mer ; l'**agent de terrain**, qui dispose des fonctions du citoyen et reçoit en plus les alertes destinées au personnel ; l'**autorité**, gestionnaire communal ou de crise ; l'**administrateur**, qui dispose des droits de l'autorité et gère en plus les comptes et les capteurs. S'y ajoutent des **acteurs non humains** : le planificateur de tâches, les capteurs et les services externes (météo, satellite, SMS, modèle de langage). Le tableau 8 présente les besoins fonctionnels retenus.", { keepNext: true }),
  ...tableBlock('Tableau', 'Besoins fonctionnels de MBEUND MI',
    ['Code', 'Besoin fonctionnel', 'Acteurs'],
    [
      ['BF1', 'S\'inscrire et s\'authentifier de manière sécurisée (mot de passe, code OTP, jeton JWT) ; créer les comptes autorité par code d\'invitation.', 'Tous ; administrateur'],
      ['BF2', 'Consulter une carte multicouche : zones de risque, épisodes d\'inondation, rues et drainage, capteurs, signalements, refuges.', 'Citoyen, autorité'],
      ['BF3', 'Signaler une inondation par l\'application (catégorie, description, photo, position) ou par SMS ; faire valider le signalement par une autorité.', 'Citoyen ; autorité'],
      ['BF4', 'Prévoir le risque par zone : prévisions météorologiques, classification du risque, prédiction du niveau d\'eau, détection satellitaire de l\'eau.', 'Planificateur'],
      ['BF5', 'Émettre et diffuser des alertes graduées (vert à rouge) par l\'application et par SMS ; permettre l\'inscription aux alertes SMS d\'une zone.', 'Autorité, planificateur ; citoyen'],
      ['BF6', 'Dialoguer avec l\'assistant NDAM, alimenté par les données réelles de la plateforme.', 'Citoyen'],
      ['BF7', 'Calculer un itinéraire d\'évacuation qui évite les tronçons à risque, vers un point de refuge.', 'Citoyen'],
      ['BF8', 'Piloter la crise : tableau de bord, triage des appels, statistiques, fiabilité du modèle, backtesting, exports PDF et CSV.', 'Autorité'],
      ['BF9', 'Renseigner son profil : vulnérabilité du foyer, relais de quartier, kit de survie, contact d\'urgence, historique des signalements.', 'Citoyen'],
    ], [800, 6170, 2100], 'analyse des besoins et code source de MBEUND MI.'),
  P("Les **besoins non fonctionnels** encadrent la qualité du système :"),
  B("**sécurité** : authentification par jeton JWT, contrôle d'accès par rôle sur chaque point d'accès de l'API, vérification par code OTP, secrets hors du code, limitation à 20 requêtes par heure pour les utilisateurs anonymes ;"),
  B("**réactivité** : traitements longs (prévisions, prédictions, analyse satellite, envoi de SMS) exécutés en tâches asynchrones avec reprises automatiques en cas d'échec, cache Redis, pagination des listes ;"),
  B("**inclusion et ergonomie** : interface adaptée au téléphone comme à l'ordinateur, attributs d'accessibilité, mode sombre, et canal SMS pour les habitants sans smartphone ;"),
  B("**confidentialité** : numéros de téléphone des inscrits réservés aux autorités, signalements limités à un rayon de 4 km autour de Thiaroye-sur-Mer ;"),
  B("**maintenabilité** : technologies libres, documentation automatique de l'API (OpenAPI), tests automatisés exécutés en intégration continue."),

  H3('Sous-section 2 : Étude et choix des méthodes de modélisation'),
  P("Deux approches de modélisation sont couramment enseignées : **Merise**, méthode française qui sépare les données et les traitements, et **UML** (Unified Modeling Language), langage graphique normalisé orienté objet. Le tableau 9 les compare au regard de notre projet.", { keepNext: true }),
  ...tableBlock('Tableau', 'Comparaison de Merise et d\'UML pour MBEUND MI',
    ['Critère', 'Merise', 'UML'],
    [
      ['Approche', 'Séparation données / traitements', 'Orientée objet, données et comportements réunis'],
      ['Adéquation au code', 'Faible avec un framework objet', 'Directe : les classes UML correspondent aux modèles Django'],
      ['Comportement dynamique', 'Peu représenté', 'Diagrammes de séquence et d\'activité'],
      ['Diffusion', 'Surtout francophone', 'Norme internationale (OMG)'],
    ], [2200, 3300, 3570], 'synthèse des auteures.'),
  P("Nous avons retenu **UML**, dont les classes se traduisent directement en modèles Django. Côté processus, un cycle en V aurait exigé des besoins figés dès le départ, ce qui ne convenait pas à un projet découvrant progressivement ses données. Nous avons donc adopté un **développement itératif et incrémental** en quatre phases : socle de données et API, sécurité et rôles, optimisations et interfaces, puis prédiction et intégration météorologique. Chaque phase a livré des fonctionnalités testées et versionnées sous Git. Les diagrammes ont été rédigés avec **PlantUML**, qui décrit les diagrammes sous forme de texte et permet de les tenir à jour avec le code."),

  H3('Sous-section 3 : Modélisation'),
  H4('a) Diagramme de cas d\'utilisation'),
  P("La figure 5 présente les cas d'utilisation, répartis entre l'espace citoyen et l'espace autorité. Les relations de généralisation traduisent la hiérarchie des rôles : l'agent de terrain hérite des cas du citoyen, l'administrateur de ceux de l'autorité."),
  ...figure('cas_utilisation.png', 600, 436, 'Figure', 'Diagramme de cas d\'utilisation de MBEUND MI', 'réalisation des auteures (PlantUML).'),
  H4('b) Diagramme de classes'),
  P("Le modèle de données compte 22 classes. La figure 6 en présente les 17 principales ; les classes de soutien (kit de survie, contact d'urgence, triage des appels, codes d'invitation, suivi d'activité des autorités) sont décrites dans le dictionnaire de données en annexe. La **ZoneRisque**, polygone géoréférencé portant ses propres seuils d'alerte, est la classe centrale : elle regroupe tronçons de rue, capteurs, prédictions, alertes, refuges et inscrits. Les classes géographiques utilisent les types PostGIS (Point, LineString, Polygon, MultiPolygon) dans le système WGS 84."),
  ...figure('classes.png', 600, 493, 'Figure', 'Diagramme de classes simplifié de MBEUND MI', 'modèles Django du projet ; réalisation des auteures (PlantUML).'),
  H4('c) Diagrammes de séquence'),
  P("La figure 7 décrit le **signalement citoyen**. L'API vérifie d'abord que le point se situe à moins de 4 km du centre de Thiaroye-sur-Mer (formule de Haversine), compresse la photo, estime le niveau d'eau visible et calcule une empreinte de l'image pour repérer les doublons. Le signalement est enregistré comme non validé ; il n'est publié qu'après validation par une autorité, ce qui protège la carte et l'assistant NDAM contre les informations erronées."),
  ...figure('seq_signalement.png', 600, 430, 'Figure', 'Diagramme de séquence du signalement citoyen', 'code de l\'API (SignalementCitoyenSerializer) ; réalisation des auteures.'),
  P("La figure 8 décrit la **prévision du risque et l'alerte**. Toutes les 6 heures, une tâche planifiée calcule pour chaque zone le cumul de pluie des 24 dernières heures, interroge le modèle Random Forest, compare le score obtenu aux seuils de la zone, puis crée une alerte et envoie des SMS au personnel et aux habitants inscrits si le niveau atteint au moins le jaune. Un second circuit, déclenché à chaque mesure reçue des capteurs, combine un classifieur en quatre niveaux et la prédiction du niveau d'eau par LSTM, et crée une alerte en cas de risque orange ou rouge."),
  ...figure('seq_alerte.png', 600, 390, 'Figure', 'Diagramme de séquence de la prévision du risque et de l\'alerte', 'code des tâches Celery (alertes/tasks.py) ; réalisation des auteures.'),

  H2('Section 2 : Implémentation et évaluation des modèles'),
  H3('Sous-section 1 : Choix technologiques et justification'),
  P("MBEUND MI suit une **architecture en trois couches**, complétée par des services asynchrones et des services externes (figure 9). La couche présentation est une application web unique pour les citoyens et les autorités. La couche application regroupe l'API REST, le serveur WebSocket, les tâches planifiées, l'écouteur des capteurs et le module d'intelligence artificielle. La couche données repose sur PostgreSQL/PostGIS et sur Redis."),
  ...figure('architecture.png', 600, 358, 'Figure', 'Architecture logique de MBEUND MI', 'réalisation des auteures.'),
  P("Chaque technologie a été choisie pour répondre à une contrainte identifiée aux chapitres précédents : accessibilité mobile, coût nul ou faible, standards ouverts et maintenabilité locale (tableau 10).", { keepNext: true }),
  ...tableBlock('Tableau', 'Choix technologiques et justification',
    ['Composant', 'Technologie retenue', 'Justification', 'Alternative écartée'],
    [
      ['Interface', 'React 18, Vite, Tailwind CSS', 'Composants réutilisables, interface adaptative, large communauté', 'Angular, jugé plus lourd'],
      ['Cartographie', 'Leaflet, tuiles OpenStreetMap', 'Bibliothèque légère et libre, adaptée au mobile', 'Google Maps, payant au-delà d\'un quota'],
      ['API', 'Django 5, Django REST Framework, SimpleJWT', 'Sécurité intégrée, ORM, administration, support SIG (GeoDjango)', 'Node.js/Express, sans SIG intégré'],
      ['Temps réel et tâches', 'Django Channels, Celery, Redis', 'WebSocket, tâches planifiées avec reprises automatiques', 'Tâches cron, sans reprise'],
      ['Base de données', 'PostgreSQL + PostGIS (Neon)', 'Standards OGC, calculs spatiaux dans la base, offre gérée', 'MongoDB, support SIG plus limité'],
      ['Intelligence artificielle', 'scikit-learn, TensorFlow/Keras', 'Bibliothèques de référence, documentées', '—'],
      ['Télédétection', 'Google Earth Engine (Sentinel-2)', 'Archive et calcul gratuits', 'Téléchargement manuel des images'],
      ['Capteurs', 'MQTT (paho-mqtt, HiveMQ Cloud)', 'Protocole léger conçu pour l\'IoT', 'Interrogation HTTP répétée'],
      ['Assistant NDAM', 'Groq (modèle gpt-oss-120b)', 'Faible latence, offre gratuite ; remplace llama-3.3-70b, retiré par Groq', '—'],
      ['SMS', 'Twilio', 'Envoi et réception de SMS par API', '—'],
      ['Hébergement', 'Render, Neon, Upstash, HiveMQ Cloud', 'Services gérés gratuits, sans serveur à administrer', 'Serveur local Docker, limité en espace disque'],
    ], [1500, 2300, 3170, 2100], 'dépendances du projet (requirements.txt, package.json) ; synthèse des auteures.'),

  H3('Sous-section 2 : Description de l\'expérimentation'),
  P("En l'absence de capteurs physiques installés, l'expérimentation a été conduite dans un **environnement de test contrôlé**, reproduisant le fonctionnement de la plateforme à Thiaroye-sur-Mer. Elle s'appuie sur quatre éléments."),
  P("**Un simulateur de capteurs.** Huit capteurs virtuels (cinq de niveau d'eau, trois pluviomètres) publient leurs mesures sur le broker MQTT, selon trois scénarios : situation normale, pluie modérée et inondation critique. Trois des cinq capteurs de niveau d'eau sont positionnés sur les lieux de l'enquête de terrain du 15 mai 2026."),
  P("**Des jeux de données de démonstration.** Des commandes d'initialisation créent les points de refuge, des tronçons de rue et des épisodes d'inondation synthétiques, déduits des pics de pluie supérieurs à 50 mm de la série Open-Meteo. Ces épisodes sont marqués comme synthétiques dans la base (champ *is_synthetic*), afin de ne jamais être confondus avec des observations réelles."),
  P("**L'entraînement des modèles.** Le classifieur en quatre niveaux est une forêt aléatoire de 50 arbres, calibrée par régression isotonique, entraînée sur 15 ans de pluie journalière (80 % des données pour l'apprentissage, 20 % pour le test). Faute de mesures historiques, le niveau d'eau est **reconstitué** à partir du cumul de pluie sur 72 heures. Le LSTM (couches de 64, 32, 16 et 1 neurones) prédit le niveau d'eau du lendemain à partir de fenêtres de 24 jours. Le modèle utilisé par la tâche planifiée est une seconde forêt aléatoire en trois classes (faible, moyen, grave), entraînée sur 25 épisodes construits pour 2020-2026 et sur les caractéristiques topographiques de 7 zones. Un modèle Isolation Forest détecte enfin les mesures de capteurs anormales. Ces choix, imposés par le manque de données de terrain, sont discutés au chapitre IV."),
  P("**Le protocole d'évaluation.** Les modèles sont évalués par l'exactitude, le score de Brier et la perte logarithmique avant et après calibration, par l'erreur absolue moyenne pour le LSTM, et par un rejeu sur les épisodes historiques (backtesting). Le logiciel est vérifié par 123 fonctions de test automatisées (112 pour le backend, 11 pour le module IA), exécutées en intégration continue sur GitHub Actions à chaque modification du backend, et par des tests manuels des parcours citoyen et autorité."),

  H3('Conclusion du chapitre'),
  P("Les besoins dégagés du terrain ont été traduits en neuf besoins fonctionnels et cinq exigences de qualité, puis modélisés en UML. L'architecture en trois couches s'appuie sur des technologies libres et des services gérés, cohérents avec les contraintes de coût et de maintenabilité. Le chapitre IV présente les données traitées, les interfaces réalisées et les résultats de l'expérimentation."),
];
